# Generated by Django 3.1.7 on 2021-03-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210317_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-active', '-valid_to'), 'verbose_name': 'kupon', 'verbose_name_plural': 'Kupony'},
        ),
    ]
