# Generated by Django 3.1.7 on 2021-03-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'kategorię', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='wood',
            options={'ordering': ('type',), 'verbose_name': 'rodzaj drewna', 'verbose_name_plural': 'Rodzaje drewna'},
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Głębokość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Wysokość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Szerokość'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.wood', verbose_name='Rodzaj drewna'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(max_length=32, verbose_name='Nazwa'),
        ),
    ]
