# Generated by Django 3.1.7 on 2021-09-20 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customizedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedproduct',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data realizacji'),
        ),
        migrations.AlterField(
            model_name='customizedproduct',
            name='file',
            field=models.FileField(blank=True, help_text='Załącz plik z rysunkiem w formacie jpg lub pdf', upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'])], verbose_name='Plik'),
        ),
    ]
