# Generated by Django 3.1.7 on 2021-10-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210920_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedproduct',
            name='status',
            field=models.CharField(choices=[('d', 'Szkic'), ('o', 'Oferta'), ('p', 'W realizacji'), ('c', 'Zrealiozwany')], default='d', max_length=2, verbose_name='Status'),
        ),
    ]
