# Generated by Django 3.1.7 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210310_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(choices=[('Natural', 'Naturalny'), ('#935B2A', 'Dąb jasny'), ('#381A10', 'Dąb ciemny'), ('#B35D32', 'Mahoń'), ('White', 'Biel'), ('#30180D', 'Orzech ciemny'), ('#5F311B', 'Orzech jasny'), ('#444213', 'Zieleń'), ('#C37437', 'Oranż'), ('Black', 'Czerń')], default='Natural', max_length=8),
        ),
    ]
