# Generated by Django 3.1.7 on 2021-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(choices=[('Natural', 'Naturalny'), ('#935B2A', 'Dąb jasny'), ('#381A10', 'Dąb ciemny'), ('#B35D32', 'Mahoń'), ('White', 'Biel'), ('#5F311B', 'Orzech'), ('#444213', 'Zieleń'), ('#C37437', 'Oranż'), ('Black', 'Czerń')], default='Natural', max_length=8),
        ),
    ]
